//! Manifest types and parsing.
//!
//! A manifest is a JSON file generated by Nix at build time that declares
//! the expected shell configuration load order and content hashes.

use serde::{Deserialize, Serialize};
use std::path::Path;

/// Top-level manifest structure.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Manifest {
    pub version: u32,
    #[serde(default)]
    pub shell: String,
    pub entries: Vec<ManifestEntry>,
}

/// A single file expected to be sourced during shell startup.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManifestEntry {
    pub phase: Phase,
    pub order: u32,
    pub path: String,
    pub kind: EntryKind,
    pub sha256: String,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub priority: Option<u32>,
    #[serde(default)]
    pub deferred: bool,
}

/// Shell startup phase.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Phase {
    Zshenv,
    Zshrc,
}

/// What kind of config file this entry represents.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum EntryKind {
    EnvInit,
    Group,
    Plugin,
    LocalOverride,
}

impl Manifest {
    /// Load a manifest from a JSON file.
    pub fn load(path: &Path) -> Result<Self, String> {
        let data =
            std::fs::read_to_string(path).map_err(|e| format!("read manifest: {path:?}: {e}"))?;
        Self::parse(&data)
    }

    /// Parse a manifest from a JSON string.
    pub fn parse(json: &str) -> Result<Self, String> {
        let manifest: Manifest =
            serde_json::from_str(json).map_err(|e| format!("parse manifest: {e}"))?;
        if manifest.version != 1 {
            return Err(format!(
                "unsupported manifest version: {}",
                manifest.version
            ));
        }
        Ok(manifest)
    }
}

impl std::fmt::Display for Phase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Phase::Zshenv => write!(f, "zshenv"),
            Phase::Zshrc => write!(f, "zshrc"),
        }
    }
}

impl std::fmt::Display for EntryKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EntryKind::EnvInit => write!(f, "env-init"),
            EntryKind::Group => write!(f, "group"),
            EntryKind::Plugin => write!(f, "plugin"),
            EntryKind::LocalOverride => write!(f, "local-override"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_valid_manifest() {
        let json = r#"{
            "version": 1,
            "shell": "zsh",
            "entries": [
                {
                    "phase": "zshenv",
                    "order": 0,
                    "path": "~/.zshenv",
                    "kind": "env-init",
                    "sha256": "abc123"
                },
                {
                    "phase": "zshrc",
                    "order": 1,
                    "path": "~/.config/shell/groups/common/settings.zsh",
                    "kind": "group",
                    "sha256": "def456",
                    "name": "common/settings"
                },
                {
                    "phase": "zshrc",
                    "order": 2,
                    "path": "~/.config/shell/plugins/skim-rs/skim/init.zsh",
                    "kind": "plugin",
                    "sha256": "ghi789",
                    "name": "skim-rs/skim",
                    "priority": 30,
                    "deferred": false
                }
            ]
        }"#;

        let manifest = Manifest::parse(json).unwrap();
        assert_eq!(manifest.version, 1);
        assert_eq!(manifest.entries.len(), 3);
        assert_eq!(manifest.entries[0].phase, Phase::Zshenv);
        assert_eq!(manifest.entries[0].kind, EntryKind::EnvInit);
        assert_eq!(manifest.entries[1].kind, EntryKind::Group);
        assert_eq!(manifest.entries[1].name.as_deref(), Some("common/settings"));
        assert_eq!(manifest.entries[2].kind, EntryKind::Plugin);
        assert_eq!(manifest.entries[2].priority, Some(30));
        assert!(!manifest.entries[2].deferred);
    }

    #[test]
    fn reject_unsupported_version() {
        let json = r#"{"version": 99, "entries": []}"#;
        assert!(Manifest::parse(json).is_err());
    }

    #[test]
    fn parse_empty_entries() {
        let json = r#"{"version": 1, "entries": []}"#;
        let manifest = Manifest::parse(json).unwrap();
        assert!(manifest.entries.is_empty());
    }

    #[test]
    fn deferred_defaults_to_false() {
        let json = r#"{
            "version": 1,
            "entries": [{
                "phase": "zshrc",
                "order": 0,
                "path": "test.zsh",
                "kind": "group",
                "sha256": "abc"
            }]
        }"#;
        let manifest = Manifest::parse(json).unwrap();
        assert!(!manifest.entries[0].deferred);
    }
}
