//! Manifest types and parsing.
//!
//! A manifest is a JSON file generated by Nix at build time that declares
//! the expected shell configuration load order and BLAKE3 content hashes,
//! composed into a Merkle root that aligns with the pleme-io tameshi
//! attestation convention (RFC 9162 domain-separated BLAKE3).

use serde::{Deserialize, Serialize};
use std::path::Path;

/// Manifest schema version understood by this crate.
///
/// Version 1 used flat SHA-256 hashes. Version 2 uses BLAKE3 with layered
/// Merkle composition matching `tameshi::signature::LayerSignature`.
pub const MANIFEST_VERSION: u32 = 2;

/// Top-level manifest structure.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Manifest {
    pub version: u32,
    #[serde(default)]
    pub shell: String,
    pub entries: Vec<ManifestEntry>,
    /// Merkle root over all layer hashes, hex-encoded BLAKE3.
    /// Optional on input (may be recomputed at verify time), always set on output.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub root: Option<String>,
}

/// A single file expected to be sourced during shell startup.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManifestEntry {
    pub phase: Phase,
    pub order: u32,
    pub path: String,
    pub kind: EntryKind,
    /// Hex-encoded BLAKE3 of the file's content.
    pub blake3: String,
    #[serde(default)]
    pub name: Option<String>,
    #[serde(default)]
    pub priority: Option<u32>,
    #[serde(default)]
    pub deferred: bool,
}

/// Shell startup phase.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Phase {
    Zshenv,
    Zshrc,
}

/// What kind of config file this entry represents.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum EntryKind {
    EnvInit,
    Group,
    Plugin,
    LocalOverride,
}

/// Canonical attestation layer, derived from `(Phase, EntryKind)`.
///
/// `PartialOrd`/`Ord` drive deterministic Merkle composition — the enum
/// variant order IS the attestation order, matching tameshi's
/// [`LayerType`] convention. Reordering breaks existing signatures.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ConfigLayer {
    ZshenvCore,
    ZshrcEnv,
    ZshrcGroups,
    ZshrcPlugins,
    ZshrcLocal,
}

impl ConfigLayer {
    #[must_use]
    pub fn from_entry(phase: Phase, kind: EntryKind) -> Self {
        match (phase, kind) {
            (Phase::Zshenv, _) => Self::ZshenvCore,
            (Phase::Zshrc, EntryKind::EnvInit) => Self::ZshrcEnv,
            (Phase::Zshrc, EntryKind::Group) => Self::ZshrcGroups,
            (Phase::Zshrc, EntryKind::Plugin) => Self::ZshrcPlugins,
            (Phase::Zshrc, EntryKind::LocalOverride) => Self::ZshrcLocal,
        }
    }
}

impl Manifest {
    /// Load a manifest from a JSON file.
    pub fn load(path: &Path) -> Result<Self, String> {
        let data =
            std::fs::read_to_string(path).map_err(|e| format!("read manifest: {path:?}: {e}"))?;
        Self::parse(&data)
    }

    /// Parse a manifest from a JSON string.
    pub fn parse(json: &str) -> Result<Self, String> {
        let manifest: Manifest =
            serde_json::from_str(json).map_err(|e| format!("parse manifest: {e}"))?;
        if manifest.version != MANIFEST_VERSION {
            return Err(format!(
                "unsupported manifest version: {} (expected {MANIFEST_VERSION})",
                manifest.version
            ));
        }
        Ok(manifest)
    }
}

impl ManifestEntry {
    /// The canonical attestation layer for this entry.
    #[must_use]
    pub fn layer(&self) -> ConfigLayer {
        ConfigLayer::from_entry(self.phase, self.kind)
    }
}

impl std::fmt::Display for Phase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Phase::Zshenv => write!(f, "zshenv"),
            Phase::Zshrc => write!(f, "zshrc"),
        }
    }
}

impl std::fmt::Display for EntryKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EntryKind::EnvInit => write!(f, "env-init"),
            EntryKind::Group => write!(f, "group"),
            EntryKind::Plugin => write!(f, "plugin"),
            EntryKind::LocalOverride => write!(f, "local-override"),
        }
    }
}

impl std::fmt::Display for ConfigLayer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ConfigLayer::ZshenvCore => write!(f, "zshenv-core"),
            ConfigLayer::ZshrcEnv => write!(f, "zshrc-env"),
            ConfigLayer::ZshrcGroups => write!(f, "zshrc-groups"),
            ConfigLayer::ZshrcPlugins => write!(f, "zshrc-plugins"),
            ConfigLayer::ZshrcLocal => write!(f, "zshrc-local"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_valid_manifest() {
        let json = r#"{
            "version": 2,
            "shell": "zsh",
            "entries": [
                {
                    "phase": "zshenv",
                    "order": 0,
                    "path": "~/.zshenv",
                    "kind": "env-init",
                    "blake3": "abc123"
                },
                {
                    "phase": "zshrc",
                    "order": 1,
                    "path": "~/.config/shell/groups/common/settings.zsh",
                    "kind": "group",
                    "blake3": "def456",
                    "name": "common/settings"
                },
                {
                    "phase": "zshrc",
                    "order": 2,
                    "path": "~/.config/shell/plugins/skim-rs/skim/init.zsh",
                    "kind": "plugin",
                    "blake3": "ghi789",
                    "name": "skim-rs/skim",
                    "priority": 30,
                    "deferred": false
                }
            ]
        }"#;

        let manifest = Manifest::parse(json).unwrap();
        assert_eq!(manifest.version, MANIFEST_VERSION);
        assert_eq!(manifest.entries.len(), 3);
        assert_eq!(manifest.entries[0].phase, Phase::Zshenv);
        assert_eq!(manifest.entries[0].kind, EntryKind::EnvInit);
        assert_eq!(manifest.entries[0].layer(), ConfigLayer::ZshenvCore);
        assert_eq!(manifest.entries[1].layer(), ConfigLayer::ZshrcGroups);
        assert_eq!(manifest.entries[2].layer(), ConfigLayer::ZshrcPlugins);
        assert_eq!(manifest.entries[1].name.as_deref(), Some("common/settings"));
        assert_eq!(manifest.entries[2].priority, Some(30));
        assert!(!manifest.entries[2].deferred);
    }

    #[test]
    fn reject_unsupported_version() {
        let json = r#"{"version": 1, "entries": []}"#;
        assert!(Manifest::parse(json).is_err());
        let json = r#"{"version": 99, "entries": []}"#;
        assert!(Manifest::parse(json).is_err());
    }

    #[test]
    fn parse_empty_entries() {
        let json = r#"{"version": 2, "entries": []}"#;
        let manifest = Manifest::parse(json).unwrap();
        assert!(manifest.entries.is_empty());
    }

    #[test]
    fn layer_ordering_is_stable() {
        // The Ord derivation defines the canonical attestation order.
        // Changing this breaks all previously-signed roots.
        assert!(ConfigLayer::ZshenvCore < ConfigLayer::ZshrcEnv);
        assert!(ConfigLayer::ZshrcEnv < ConfigLayer::ZshrcGroups);
        assert!(ConfigLayer::ZshrcGroups < ConfigLayer::ZshrcPlugins);
        assert!(ConfigLayer::ZshrcPlugins < ConfigLayer::ZshrcLocal);
    }
}
